In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')


In [27]:
data=pd.read_csv("test.csv")

In [28]:
data.head()

,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)",subject,Activity
0,0.257178,-0.023285,-0.014654,-0.938404,-0.920091,-0.667683,-0.952501,-0.925249,-0.674302,-0.894088,...,-0.705974,0.006462,0.162920,-0.825886,0.271151,-0.720009,0.276801,-0.057978,2,STANDING
1,0.286027,-0.013163,-0.119083,-0.975415,-0.967458,-0.944958,-0.986799,-0.968401,-0.945823,-0.894088,...,-0.594944,-0.083495,0.017500,-0.434375,0.920593,-0.698091,0.281343,-0.083898,2,STANDING
2,0.275485,-0.026050,-0.118152,-0.993819,-0.969926,-0.962748,-0.994403,-0.970735,-0.963483,-0.939260,...,-0.640736,-0.034956,0.202302,0.064103,0.145068,-0.702771,0.280083,-0.079346,2,STANDING
3,0.270298,-0.032614,-0.117520,-0.994743,-0.973268,-0.967091,-0.995274,-0.974471,-0.968897,-0.938610,...,-0.736124,-0.017067,0.154438,0.340134,0.296407,-0.698954,0.284114,-0.077108,2,STANDING
4,0.274833,-0.027848,-0.129527,-0.993852,-0.967445,-0.978295,-0.994111,-0.965953,-0.977346,-0.938610,...,-0.846595,-0.002223,-0.040046,0.736715,-0.118545,-0.692245,0.290722,-0.073857,2,STANDING


In [29]:
data.columns

Index(['tBodyAcc-mean()-X', 'tBodyAcc-mean()-Y', 'tBodyAcc-mean()-Z',
       'tBodyAcc-std()-X', 'tBodyAcc-std()-Y', 'tBodyAcc-std()-Z',
       'tBodyAcc-mad()-X', 'tBodyAcc-mad()-Y', 'tBodyAcc-mad()-Z',
       'tBodyAcc-max()-X',
       ...
       'fBodyBodyGyroJerkMag-kurtosis()', 'angle(tBodyAccMean,gravity)',
       'angle(tBodyAccJerkMean),gravityMean)',
       'angle(tBodyGyroMean,gravityMean)',
       'angle(tBodyGyroJerkMean,gravityMean)', 'angle(X,gravityMean)',
       'angle(Y,gravityMean)', 'angle(Z,gravityMean)', 'subject', 'Activity'],
      dtype='object', length=563)

In [30]:
data.shape

(2947, 563)

In [31]:
features=data.iloc[:,:-2]

In [32]:
features.shape

(2947, 561)

In [33]:
target=data.iloc[:,-1]

In [34]:
from sklearn.preprocessing import LabelEncoder

In [35]:
le = LabelEncoder()
target = le.fit_transform(target)

In [36]:
le.classes_

array(['LAYING', 'SITTING', 'STANDING', 'WALKING', 'WALKING_DOWNSTAIRS',
       'WALKING_UPSTAIRS'], dtype=object)

In [37]:
target.shape

(2947,)

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
X_train, X_test, y_train, y_test = train_test_split(
    features,
    target,
    test_size=0.2,
    random_state=42)

In [40]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape  )

(2357, 561)
(590, 561)
(2357,)
(590,)


In [41]:
for i, label in enumerate(le.classes_):
    print(i, "->", label)

0 -> LAYING
1 -> SITTING
2 -> STANDING
3 -> WALKING
4 -> WALKING_DOWNSTAIRS
5 -> WALKING_UPSTAIRS


In [42]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()

model.add(Dense(128, activation='relu', input_shape=(561,)))
model.add(Dense(64, activation='relu'))
model.add(Dense(6, activation='softmax'))

In [43]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [44]:
history = model.fit(
    X_train,
    y_train,
    epochs=10,
    validation_data=(X_test, y_test)
)


Epoch 1/10
74/74 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7191 - loss: 0.7491 - val_accuracy: 0.9034 - val_loss: 0.3303
Epoch 2/10
74/74 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9228 - loss: 0.2490 - val_accuracy: 0.9746 - val_loss: 0.1449
Epoch 3/10
74/74 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9372 - loss: 0.1742 - val_accuracy: 0.9644 - val_loss: 0.1136
Epoch 4/10
74/74 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9478 - loss: 0.1362 - val_accuracy: 0.9847 - val_loss: 0.0765
Epoch 5/10
74/74 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9652 - loss: 0.0969 - val_accuracy: 0.9746 - val_loss: 0.0721
Epoch 6/10
74/74 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9605 - loss: 0.1016 - val_accuracy: 0.9729 - val_loss: 0.0683
Epoch 7/10
74/74 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9745 - loss: 0.0751 - val_accuracy: 0.9898 - val_loss: 0.0439
Epoch 8/10
74/74 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9750 - loss: 0.0695 - val_accuracy: 0.9627 - val_loss:

In [45]:
loss, accuracy = model.evaluate(X_test, y_test)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9763 - loss: 0.0560 
Test Loss: 0.05595330148935318
Test Accuracy: 0.9762712121009827


In [46]:
pred = model.predict(X_test)

import numpy as np
predicted = np.argmax(pred, axis=1)

19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 


In [47]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, predicted))

print(classification_report(y_test, predicted))

[[106   0   0   0   0   0]
 [  0 102   1   0   0   0]
 [  0  11  85   0   0   0]
 [  0   0   0  96   1   0]
 [  0   0   0   0  83   0]
 [  0   0   0   0   1 104]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       106
           1       0.90      0.99      0.94       103
           2       0.99      0.89      0.93        96
           3       1.00      0.99      0.99        97
           4       0.98      1.00      0.99        83
           5       1.00      0.99      1.00       105

    accuracy                           0.98       590
   macro avg       0.98      0.98      0.98       590
weighted avg       0.98      0.98      0.98       590



In [48]:
# Define different hidden layer architectures to test
# Each tuple represents the nodes in (Layer 1, Layer 2, Layer 3...)
architectures = [
    (64,),                 # 1 Layer: 64 nodes
    (128,),                # 1 Layer: 128 nodes
    (64, 32),              # 2 Layers: 64 nodes then 32 nodes
    (128, 64),             # 2 Layers: 128 nodes then 64 nodes
    (128, 64, 32)          # 3 Layers: 128 -> 64 -> 32 nodes
]

best_accuracy = 0.0
best_config = None

for config in architectures:
    print(f"\n--- Testing Architecture Layout: {config} ---")
    
    # 1. Start a fresh sequential model container
    model = Sequential()
    
    # 2. Add the very first hidden layer with the input shape requirement
    model.add(Dense(config[0], activation='relu', input_shape=(561,)))
    
    # 3. Add any remaining hidden layers dynamically using a loop
    for node_count in config[1:]:
        model.add(Dense(node_count, activation='relu'))
        
    # 4. Add the final output layer (6 classes for your 6 encoded actions)
    model.add(Dense(6, activation='softmax'))
    
    # 5. Compile the loop model configuration
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    
    # 6. Train the model (verbose=0 turns off the massive text spam)
    # Using your updated variable name y_train_encoded
    history = model.fit(X_train, y_train, epochs=10, batch_size=32, 
                        validation_data=(X_test, y_test), verbose=0)
    
    # 7. Extract the validation accuracy score from the final epoch
    current_val_acc = history.history['val_accuracy'][-1]
    print(f"Layout {config} -> Validation Accuracy: {current_val_acc * 100:.2f}%")
    
    # 8. Check if this is our highest performer so far
    if current_val_acc > best_accuracy:
        best_accuracy = current_val_acc
        best_config = config

print("\n🏆 Grid Search Optimization Finished!")
print(f"The best overall layer architecture is: {best_config} with a score of {best_accuracy*100:.2f}%")


--- Testing Architecture Layout: (64,) ---
Layout (64,) -> Validation Accuracy: 92.88%

--- Testing Architecture Layout: (128,) ---
Layout (128,) -> Validation Accuracy: 92.37%

--- Testing Architecture Layout: (64, 32) ---
Layout (64, 32) -> Validation Accuracy: 97.97%

--- Testing Architecture Layout: (128, 64) ---
Layout (128, 64) -> Validation Accuracy: 98.64%

--- Testing Architecture Layout: (128, 64, 32) ---
Layout (128, 64, 32) -> Validation Accuracy: 97.63%

🏆 Grid Search Optimization Finished!
The best overall layer architecture is: (128, 64) with a score of 98.64%


In [49]:
#since we know 128,64 is best performing so we will save it now 

In [50]:
model.save("scribble_model.keras")